default: &default
  adapter: sqlite3
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  default_transaction_mode: IMMEDIATE

databases: &databases
  primary:
    <<: *default
    database: storage/koal_<%= Rails.env %>.sqlite3
  cache:
    <<: *default
    database: storage/koal_<%= Rails.env %>_cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: storage/koal_<%= Rails.env %>_queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: storage/koal_<%= Rails.env %>_cable.sqlite3
    migrations_paths: db/cable_migrate
  errors:
    <<: *default
    database: storage/koal_<%= Rails.env %>_errors.sqlite3
    migrations_paths: db/errors_migrate

development:
  <<: *databases

test:
  <<: *default
  database: storage/koal_test.sqlite3

production:
  <<: *databases
